import { ReactNode } from "react";

export type ResourceField = {
  key: string;
  label: string;
  type?: "text" | "number" | "select" | "date" | "checkbox";
  required?: boolean;
  readOnly?: boolean;
  options?: { label: string; value: string | number }[];
  placeholder?: string;
};

export type ResourceColumn<T = any> = {
  key: keyof T | string;
  label: string;
  render?: (row: T) => ReactNode;
};

export type ResourceConfig<T = any> = {
  key: string;
  path: string;
  title: string;
  description?: string;
  table: string;
  idKey: string;
  orderBy?: string;
  searchColumns?: string[];
  columns: ResourceColumn<T>[];
  fields: ResourceField[];
  initialValues?: Record<string, any>;
};

export const RESOURCE_CONFIG: Record<string, ResourceConfig> = {
  accounts: {
    key: "accounts",
    path: "/accounts",
    title: "Cuentas contables",
    description: "Plan de cuentas para movimientos contables.",
    table: "accounts",
    idKey: "accacc_id",
    orderBy: "accacc_id",
    searchColumns: ["accacc_name", "accacc_number"],
    columns: [
      { key: "accacc_id", label: "ID" },
      { key: "accacc_name", label: "Nombre" },
      { key: "accacc_number", label: "Numero" },
    ],
    fields: [
      { key: "accacc_name", label: "Nombre", required: true },
      { key: "accacc_number", label: "Numero" },
    ],
  },
  banks_accounts: {
    key: "banks_accounts",
    path: "/banks_accounts",
    title: "Cuentas bancarias",
    description: "Registro de cuentas bancarias para pagos.",
    table: "bank_accounts",
    idKey: "bacc_id",
    orderBy: "bacc_id",
    searchColumns: ["bacc_bank", "bacc_number", "bacc_owner_name"],
    columns: [
      { key: "bacc_bank", label: "Banco" },
      { key: "bacc_number", label: "Numero" },
      { key: "bacc_owner_name", label: "Titular" },
      { key: "bacc_active", label: "Activa" },
    ],
    fields: [
      { key: "user_id", label: "Usuario ID", type: "number" },
      { key: "std_id", label: "Estudio ID", type: "number" },
      { key: "bacc_bank", label: "Banco", required: true },
      { key: "bacc_type", label: "Tipo" },
      { key: "bacc_number", label: "Numero", required: true },
      { key: "bacc_owner_name", label: "Titular" },
      { key: "bacc_owner_id", label: "Documento titular" },
      { key: "bacc_active", label: "Activa", type: "checkbox" },
    ],
    initialValues: { bacc_active: true },
  },
  products: {
    key: "products",
    path: "/products",
    title: "Productos",
    description: "Catalogo de productos y servicios.",
    table: "products",
    idKey: "prod_id",
    orderBy: "prod_id",
    searchColumns: ["prod_code", "prod_name"],
    columns: [
      { key: "prod_code", label: "Codigo" },
      { key: "prod_name", label: "Nombre" },
      { key: "cate_id", label: "Categoria ID" },
      { key: "prod_sale_price", label: "Precio venta" },
    ],
    fields: [
      { key: "cate_id", label: "Categoria ID", type: "number", required: true },
      { key: "prod_code", label: "Codigo", required: true },
      { key: "prod_name", label: "Nombre", required: true },
      { key: "prod_purchase_price", label: "Precio compra", type: "number" },
      { key: "prod_wholesaler_price", label: "Precio mayorista", type: "number" },
      { key: "prod_sale_price", label: "Precio venta", type: "number" },
      { key: "prod_stock", label: "Stock", type: "number" },
      { key: "transtype_id", label: "Tipo transaccion ID", type: "number" },
    ],
  },
  transactions: {
    key: "transactions",
    path: "/transactions",
    title: "Transacciones",
    description: "Registro contable de ingresos y egresos.",
    table: "transactions",
    idKey: "trans_id",
    orderBy: "trans_id",
    searchColumns: ["trans_description"],
    columns: [
      { key: "trans_date", label: "Fecha" },
      { key: "transtype_id", label: "Tipo ID" },
      { key: "user_id", label: "Usuario ID" },
      { key: "trans_amount", label: "Monto" },
    ],
    fields: [
      { key: "transtype_id", label: "Tipo ID", type: "number", required: true },
      { key: "user_id", label: "Usuario ID", type: "number", required: true },
      { key: "trans_date", label: "Fecha", type: "date", required: true },
      { key: "trans_amount", label: "Monto", type: "number", required: true },
      { key: "trans_description", label: "Descripcion" },
      { key: "prod_id", label: "Producto ID", type: "number" },
      { key: "trans_quantity", label: "Cantidad", type: "number" },
      { key: "trans_rtefte", label: "Aplica Rte Fte", type: "checkbox" },
      { key: "stdmod_id", label: "Contrato ID", type: "number" },
      { key: "period_id", label: "Periodo ID", type: "number" },
      { key: "trans_pendingbalance", label: "Saldo pendiente", type: "checkbox" },
    ],
    initialValues: { trans_rtefte: false, trans_pendingbalance: false },
  },
  payments: {
    key: "payments",
    path: "/payments",
    title: "Pagos",
    description: "Liquidaciones y pagos a modelos.",
    table: "payments",
    idKey: "pay_id",
    orderBy: "pay_id",
    searchColumns: ["pay_status"],
    columns: [
      { key: "pay_amount", label: "Monto" },
      { key: "pay_currency", label: "Moneda" },
      { key: "pay_status", label: "Estado" },
      { key: "pay_date", label: "Fecha" },
    ],
    fields: [
      { key: "user_id", label: "Usuario ID", type: "number" },
      { key: "std_id", label: "Estudio ID", type: "number" },
      { key: "period_id", label: "Periodo ID", type: "number" },
      { key: "pay_amount", label: "Monto", type: "number", required: true },
      { key: "pay_currency", label: "Moneda" },
      { key: "pay_status", label: "Estado" },
      { key: "pay_date", label: "Fecha", type: "date" },
      { key: "pay_exchange_rate", label: "TRM", type: "number" },
      { key: "pay_notes", label: "Notas" },
    ],
    initialValues: { pay_currency: "COP", pay_status: "PENDING" },
  },
  payments_files: {
    key: "payments_files",
    path: "/payments_files",
    title: "Archivos de pago",
    description: "Comprobantes y archivos adjuntos de pagos.",
    table: "payment_files",
    idKey: "payf_id",
    orderBy: "payf_id",
    searchColumns: ["payf_name", "payf_type"],
    columns: [
      { key: "pay_id", label: "Pago ID" },
      { key: "payf_name", label: "Nombre" },
      { key: "payf_type", label: "Tipo" },
      { key: "payf_total", label: "Total" },
    ],
    fields: [
      { key: "pay_id", label: "Pago ID", type: "number", required: true },
      { key: "payf_name", label: "Nombre" },
      { key: "payf_url", label: "URL" },
      { key: "payf_type", label: "Tipo" },
      { key: "payf_total", label: "Total", type: "number" },
    ],
  },
  periods: {
    key: "periods",
    path: "/periods",
    title: "Periodos",
    description: "Gestion de periodos de liquidacion.",
    table: "periods",
    idKey: "period_id",
    orderBy: "period_id",
    searchColumns: ["period_state"],
    columns: [
      { key: "period_start_date", label: "Inicio" },
      { key: "period_end_date", label: "Fin" },
      { key: "period_state", label: "Estado" },
      { key: "period_closed_date", label: "Cerrado" },
    ],
    fields: [
      { key: "period_start_date", label: "Inicio", type: "date", required: true },
      { key: "period_end_date", label: "Fin", type: "date", required: true },
      { key: "period_state", label: "Estado", required: true },
      { key: "period_observation", label: "Observacion" },
      { key: "user_id", label: "Usuario ID", type: "number" },
      { key: "period_closed_date", label: "Cerrado", type: "date" },
      { key: "liquidated_at", label: "Liquidado", type: "date" },
    ],
    initialValues: { period_state: "OPEN" },
  },
  notifications: {
    key: "notifications",
    path: "/notifications",
    title: "Notificaciones",
    description: "Avisos internos del sistema.",
    table: "notifications",
    idKey: "noti_id",
    orderBy: "noti_id",
    searchColumns: ["noti_title", "noti_menu"],
    columns: [
      { key: "noti_title", label: "Titulo" },
      { key: "noti_menu", label: "Menu" },
      { key: "noti_type", label: "Tipo" },
      { key: "noti_read", label: "Leida" },
    ],
    fields: [
      { key: "user_id", label: "Usuario ID", type: "number" },
      { key: "user_id_to_notify", label: "Usuario destino", type: "number" },
      { key: "noti_type", label: "Tipo" },
      { key: "noti_title", label: "Titulo", required: true },
      { key: "noti_data", label: "Detalle", required: true },
      { key: "noti_menu", label: "Menu", required: true },
      { key: "noti_read", label: "Leida", type: "checkbox" },
    ],
    initialValues: { noti_read: false },
  },
  petitions: {
    key: "petitions",
    path: "/petitions",
    title: "Solicitudes",
    description: "Peticiones operativas de las modelos.",
    table: "petitions",
    idKey: "ptn_id",
    orderBy: "ptn_id",
    searchColumns: ["ptn_type", "ptn_page", "ptn_nick"],
    columns: [
      { key: "ptn_type", label: "Tipo" },
      { key: "ptn_page", label: "Pagina" },
      { key: "ptn_state", label: "Estado" },
      { key: "user_id", label: "Usuario ID" },
    ],
    fields: [
      { key: "user_id", label: "Usuario ID", type: "number", required: true },
      { key: "ptn_consecutive", label: "Consecutivo", type: "number" },
      { key: "ptn_type", label: "Tipo" },
      { key: "ptn_nick", label: "Nick" },
      { key: "ptn_password", label: "Password" },
      { key: "ptn_page", label: "Pagina" },
      { key: "ptn_state", label: "Estado" },
      { key: "ptn_observation", label: "Observacion" },
      { key: "ptn_mail", label: "Correo" },
      { key: "ptn_linkacc", label: "Link" },
    ],
    initialValues: { ptn_state: "PENDING" },
  },
  logs: {
    key: "logs",
    path: "/logs",
    title: "Logs",
    description: "Auditoria de cambios en el sistema.",
    table: "logs",
    idKey: "log_id",
    orderBy: "log_id",
    searchColumns: ["log_action", "log_entity", "log_entity_id"],
    columns: [
      { key: "log_action", label: "Accion" },
      { key: "log_entity", label: "Entidad" },
      { key: "log_entity_id", label: "Entidad ID" },
      { key: "log_ip", label: "IP" },
    ],
    fields: [
      { key: "user_id", label: "Usuario ID", type: "number" },
      { key: "log_action", label: "Accion" },
      { key: "log_entity", label: "Entidad" },
      { key: "log_entity_id", label: "Entidad ID" },
      { key: "log_ip", label: "IP" },
      { key: "log_old_data", label: "Datos anteriores" },
      { key: "log_new_data", label: "Datos nuevos" },
    ],
  },
  login_history: {
    key: "login_history",
    path: "/login_history",
    title: "Historial de sesiones",
    description: "Registro de accesos al sistema.",
    table: "login_history",
    idKey: "lhist_id",
    orderBy: "lhist_id",
    searchColumns: ["lhist_ip", "lhist_device"],
    columns: [
      { key: "user_id", label: "Usuario ID" },
      { key: "lhist_ip", label: "IP" },
      { key: "lhist_device", label: "Dispositivo" },
      { key: "lhist_success", label: "Exito" },
    ],
    fields: [
      { key: "user_id", label: "Usuario ID", type: "number" },
      { key: "lhist_ip", label: "IP" },
      { key: "lhist_device", label: "Dispositivo" },
      { key: "lhist_success", label: "Exito", type: "checkbox" },
    ],
    initialValues: { lhist_success: true },
  },
  locations: {
    key: "locations",
    path: "/locations",
    title: "Localizaciones",
    description: "Pais, departamento y ciudad.",
    table: "locations",
    idKey: "loc_id",
    orderBy: "loc_id",
    searchColumns: ["loc_country", "loc_department", "loc_city"],
    columns: [
      { key: "loc_country", label: "Pais" },
      { key: "loc_department", label: "Departamento" },
      { key: "loc_city", label: "Ciudad" },
      { key: "loc_active", label: "Activa" },
    ],
    fields: [
      { key: "loc_country", label: "Pais" },
      { key: "loc_department", label: "Departamento" },
      { key: "loc_city", label: "Ciudad" },
      { key: "loc_active", label: "Activa", type: "checkbox" },
    ],
    initialValues: { loc_active: true },
  },
  studios_rooms: {
    key: "studios_rooms",
    path: "/studios_rooms",
    title: "Cuartos",
    description: "Cuartos y disponibilidad por estudio.",
    table: "studios_rooms",
    idKey: "stdroom_id",
    orderBy: "stdroom_id",
    searchColumns: ["stdroom_name"],
    columns: [
      { key: "std_id", label: "Estudio ID" },
      { key: "stdroom_name", label: "Nombre" },
      { key: "stdroom_consecutive", label: "Consecutivo" },
      { key: "stdroom_active", label: "Activo" },
    ],
    fields: [
      { key: "std_id", label: "Estudio ID", type: "number", required: true },
      { key: "stdroom_name", label: "Nombre", required: true },
      { key: "stdroom_consecutive", label: "Consecutivo", type: "number" },
      { key: "stdroom_active", label: "Activo", type: "checkbox" },
      { key: "stdroom_occupied", label: "Ocupado", type: "checkbox" },
    ],
    initialValues: { stdroom_active: true, stdroom_occupied: false },
  },
  studios_shifts: {
    key: "studios_shifts",
    path: "/studios_shifts",
    title: "Turnos",
    description: "Turnos y horarios de estudio.",
    table: "studios_shifts",
    idKey: "stdshift_id",
    orderBy: "stdshift_id",
    searchColumns: ["stdshift_name"],
    columns: [
      { key: "std_id", label: "Estudio ID" },
      { key: "stdshift_name", label: "Nombre" },
      { key: "stdshift_begin_time", label: "Inicio" },
      { key: "stdshift_finish_time", label: "Fin" },
    ],
    fields: [
      { key: "std_id", label: "Estudio ID", type: "number", required: true },
      { key: "stdshift_name", label: "Nombre", required: true },
      { key: "stdshift_begin_time", label: "Inicio" },
      { key: "stdshift_finish_time", label: "Fin" },
      { key: "stdshift_capacity", label: "Capacidad", type: "number" },
    ],
  },
  studios_accounts: {
    key: "studios_accounts",
    path: "/studios_accounts",
    title: "Cuentas del estudio",
    description: "Cuentas de plataformas por estudio.",
    table: "studios_accounts",
    idKey: "stdacc_id",
    orderBy: "stdacc_id",
    searchColumns: ["stdacc_app", "stdacc_username"],
    columns: [
      { key: "std_id", label: "Estudio ID" },
      { key: "stdacc_app", label: "App" },
      { key: "stdacc_username", label: "Usuario" },
      { key: "stdacc_active", label: "Activo" },
    ],
    fields: [
      { key: "std_id", label: "Estudio ID", type: "number", required: true },
      { key: "stdacc_app", label: "Aplicacion", required: true },
      { key: "stdacc_username", label: "Usuario", required: true },
      { key: "stdacc_password", label: "Password" },
      { key: "stdacc_apikey", label: "API Key" },
      { key: "stdacc_active", label: "Activo", type: "checkbox" },
      { key: "stdacc_fail_message", label: "Mensaje fallo" },
      { key: "stdacc_fail_count", label: "Fallos", type: "number" },
    ],
    initialValues: { stdacc_active: true },
  },
  studios_models: {
    key: "studios_models",
    path: "/studios_models",
    title: "Contratos de modelos",
    description: "Asignaciones de modelos a estudios.",
    table: "studios_models",
    idKey: "stdmod_id",
    orderBy: "stdmod_id",
    searchColumns: ["stdmod_contract_type"],
    columns: [
      { key: "std_id", label: "Estudio ID" },
      { key: "user_id_model", label: "Modelo ID" },
      { key: "stdroom_id", label: "Cuarto ID" },
      { key: "stdshift_id", label: "Turno ID" },
      { key: "stdmod_active", label: "Activo" },
    ],
    fields: [
      { key: "std_id", label: "Estudio ID", type: "number", required: true },
      { key: "user_id_model", label: "Modelo ID", type: "number", required: true },
      { key: "stdmod_start_at", label: "Inicio", type: "date", required: true },
      { key: "stdmod_finish_at", label: "Fin", type: "date" },
      { key: "stdmod_active", label: "Activo", type: "checkbox" },
      { key: "stdroom_id", label: "Cuarto ID", type: "number" },
      { key: "stdshift_id", label: "Turno ID", type: "number" },
      { key: "stdmod_percent", label: "Porcentaje", type: "number" },
      { key: "stdmod_rtefte", label: "Rte Fte", type: "checkbox" },
      { key: "stdmod_contract_type", label: "Tipo contrato" },
      { key: "stdmod_contract_number", label: "Numero contrato", type: "number" },
      { key: "stdmod_goal", label: "Meta", type: "number" },
      { key: "stdmod_position", label: "Cargo" },
    ],
    initialValues: { stdmod_active: true },
  },
  models_accounts: {
    key: "models_accounts",
    path: "/models_accounts",
    title: "Cuentas de modelos",
    description: "Cuentas de plataformas por modelo.",
    table: "models_accounts",
    idKey: "modacc_id",
    orderBy: "modacc_id",
    searchColumns: ["modacc_app", "modacc_username"],
    columns: [
      { key: "stdmod_id", label: "Contrato ID" },
      { key: "modacc_app", label: "App" },
      { key: "modacc_username", label: "Usuario" },
      { key: "modacc_state", label: "Estado" },
      { key: "modacc_active", label: "Activo" },
    ],
    fields: [
      { key: "stdmod_id", label: "Contrato ID", type: "number", required: true },
      { key: "modacc_app", label: "Aplicacion", required: true },
      { key: "modacc_username", label: "Usuario", required: true },
      { key: "modacc_password", label: "Password", required: true },
      { key: "modacc_state", label: "Estado", required: true },
      { key: "modacc_active", label: "Activo", type: "checkbox" },
      { key: "modacc_mail", label: "Correo" },
      { key: "modacc_linkacc", label: "Link" },
      { key: "modacc_payment_username", label: "Usuario pago" },
    ],
    initialValues: { modacc_active: true },
  },
  models_goals: {
    key: "models_goals",
    path: "/models_goals",
    title: "Metas",
    description: "Metas asignadas a modelos.",
    table: "models_goals",
    idKey: "modgoal_id",
    orderBy: "modgoal_id",
    searchColumns: ["modgoal_type"],
    columns: [
      { key: "stdmod_id", label: "Contrato ID" },
      { key: "modgoal_type", label: "Tipo" },
      { key: "modgoal_amount", label: "Monto" },
      { key: "modgoal_percent", label: "%" },
    ],
    fields: [
      { key: "stdmod_id", label: "Contrato ID", type: "number", required: true },
      { key: "modgoal_type", label: "Tipo" },
      { key: "modgoal_amount", label: "Monto", type: "number", required: true },
      { key: "modgoal_percent", label: "Porcentaje", type: "number" },
      { key: "modgoal_auto", label: "Auto", type: "checkbox" },
      { key: "modgoal_date", label: "Fecha", type: "date" },
      { key: "modgoal_reach_goal", label: "Meta alcanzada", type: "checkbox" },
    ],
    initialValues: { modgoal_auto: false, modgoal_reach_goal: false },
  },
  models_streams: {
    key: "models_streams",
    path: "/models_streams",
    title: "Streams",
    description: "Sesiones de transmision por modelo.",
    table: "models_streams",
    idKey: "modstr_id",
    orderBy: "modstr_id",
    searchColumns: ["modstr_period", "modstr_source"],
    columns: [
      { key: "modacc_id", label: "Cuenta ID" },
      { key: "modstr_date", label: "Fecha" },
      { key: "modstr_period", label: "Periodo" },
      { key: "modstr_earnings_value", label: "Ingreso" },
    ],
    fields: [
      { key: "modacc_id", label: "Cuenta ID", type: "number", required: true },
      { key: "modstr_date", label: "Fecha", type: "date", required: true },
      { key: "modstr_period", label: "Periodo", required: true },
      { key: "modstr_earnings_value", label: "Ingreso", type: "number", required: true },
      { key: "modstr_earnings_usd", label: "USD", type: "number" },
      { key: "modstr_earnings_eur", label: "EUR", type: "number" },
      { key: "modstr_earnings_cop", label: "COP", type: "number" },
      { key: "modstr_time", label: "Tiempo", type: "number" },
      { key: "modstrfile_id", label: "Archivo ID", type: "number" },
      { key: "stdmod_id", label: "Contrato ID", type: "number" },
      { key: "std_id", label: "Estudio ID", type: "number" },
      { key: "period_id", label: "Periodo ID", type: "number" },
      { key: "modstr_source", label: "Fuente" },
    ],
  },
  models_streams_customers: {
    key: "models_streams_customers",
    path: "/models_streams_customers",
    title: "Clientes de streams",
    description: "Clientes registrados durante transmisiones.",
    table: "models_streams_customers",
    idKey: "modstrcus_id",
    orderBy: "modstrcus_id",
    searchColumns: ["modstrcus_name", "modstrcus_account"],
    columns: [
      { key: "modstr_id", label: "Stream ID" },
      { key: "modstrcus_name", label: "Nombre" },
      { key: "modstrcus_earnings", label: "Ingreso" },
      { key: "modstrcus_received_at", label: "Fecha" },
    ],
    fields: [
      { key: "modstr_id", label: "Stream ID", type: "number", required: true },
      { key: "modstrcus_name", label: "Nombre", required: true },
      { key: "modstrcus_account", label: "Cuenta" },
      { key: "modstrcus_website", label: "Website" },
      { key: "modstrcus_product", label: "Producto" },
      { key: "modstrcus_price", label: "Precio", type: "number" },
      { key: "modstrcus_earnings", label: "Ingreso", type: "number", required: true },
      { key: "modstrcus_received_at", label: "Recibido", required: true },
      { key: "modstrcus_chat_duration", label: "Duracion chat", type: "number" },
    ],
  },
  models_streams_files: {
    key: "models_streams_files",
    path: "/models_streams_files",
    title: "Archivos de streams",
    description: "Archivos asociados a streams.",
    table: "models_streams_files",
    idKey: "modstrfile_id",
    orderBy: "modstrfile_id",
    searchColumns: ["modstrfile_description", "modstrfile_filename"],
    columns: [
      { key: "modstrfile_description", label: "Descripcion" },
      { key: "modstrfile_filename", label: "Archivo" },
      { key: "modstrfile_template", label: "Plantilla" },
      { key: "created_by", label: "Creado por" },
    ],
    fields: [
      { key: "modstrfile_description", label: "Descripcion", required: true },
      { key: "modstrfile_filename", label: "Archivo", required: true },
      { key: "modstrfile_template", label: "Plantilla", required: true },
      { key: "created_by", label: "Creado por", type: "number" },
    ],
  },
  models_transactions: {
    key: "models_transactions",
    path: "/models_transactions",
    title: "Transacciones de modelos",
    description: "Movimientos financieros por modelo.",
    table: "models_transactions",
    idKey: "modtrans_id",
    orderBy: "modtrans_id",
    searchColumns: ["modtrans_description"],
    columns: [
      { key: "stdmod_id", label: "Contrato ID" },
      { key: "transtype_id", label: "Tipo ID" },
      { key: "modtrans_date", label: "Fecha" },
      { key: "modtrans_amount", label: "Monto" },
    ],
    fields: [
      { key: "stdmod_id", label: "Contrato ID", type: "number", required: true },
      { key: "transtype_id", label: "Tipo ID", type: "number", required: true },
      { key: "modtrans_date", label: "Fecha", type: "date", required: true },
      { key: "modtrans_amount", label: "Monto", type: "number", required: true },
      { key: "modtrans_description", label: "Descripcion" },
      { key: "prod_id", label: "Producto ID", type: "number" },
      { key: "modtrans_quantity", label: "Cantidad", type: "number" },
      { key: "modtrans_rtefte", label: "Rte Fte", type: "checkbox" },
    ],
    initialValues: { modtrans_rtefte: false },
  },
  monitors: {
    key: "monitors",
    path: "/monitors",
    title: "Monitores",
    description: "Relaciones entre monitores y modelos.",
    table: "monitors_relations",
    idKey: "user_parent_id",
    orderBy: "user_parent_id",
    searchColumns: ["user_parent_id", "user_child_id"],
    columns: [
      { key: "user_parent_id", label: "Monitor ID" },
      { key: "user_child_id", label: "Modelo ID" },
    ],
    fields: [
      { key: "user_parent_id", label: "Monitor ID", type: "number", required: true },
      { key: "user_child_id", label: "Modelo ID", type: "number", required: true },
    ],
  },
  commissions: {
    key: "commissions",
    path: "/commissions",
    title: "Comisiones",
    description: "Configuracion de comisiones por estudio o usuario.",
    table: "commissions",
    idKey: "com_id",
    orderBy: "com_id",
    searchColumns: ["com_type", "com_currency"],
    columns: [
      { key: "std_id", label: "Estudio ID" },
      { key: "user_id", label: "Usuario ID" },
      { key: "com_type", label: "Tipo" },
      { key: "com_percentage", label: "%" },
      { key: "com_active", label: "Activa" },
    ],
    fields: [
      { key: "std_id", label: "Estudio ID", type: "number" },
      { key: "user_id", label: "Usuario ID", type: "number" },
      { key: "com_type", label: "Tipo" },
      { key: "com_percentage", label: "%", type: "number" },
      { key: "com_fixed_amount", label: "Valor fijo", type: "number" },
      { key: "com_currency", label: "Moneda" },
      { key: "com_active", label: "Activa", type: "checkbox" },
      { key: "period_id", label: "Periodo ID", type: "number" },
    ],
    initialValues: { com_active: true, com_currency: "USD" },
  },
  setup_commissions: {
    key: "setup_commissions",
    path: "/setup_commissions",
    title: "Config. comisiones",
    description: "Escalas y configuraciones de comisiones.",
    table: "setup_commissions",
    idKey: "setcomm_id",
    orderBy: "setcomm_id",
    searchColumns: ["setcomm_title"],
    columns: [
      { key: "setcomm_title", label: "Titulo" },
      { key: "std_id", label: "Estudio ID" },
    ],
    fields: [
      { key: "setcomm_title", label: "Titulo", required: true },
      { key: "std_id", label: "Estudio ID", type: "number" },
    ],
  },
  api_modules: {
    key: "api_modules",
    path: "/api_modules",
    title: "Modulos API",
    description: "Registro de modulos y permisos.",
    table: "api_modules",
    idKey: "module_id",
    orderBy: "module_id",
    searchColumns: ["module_key", "module_name", "module_group"],
    columns: [
      { key: "module_key", label: "Key" },
      { key: "module_name", label: "Nombre" },
      { key: "module_group", label: "Grupo" },
      { key: "is_active", label: "Activo" },
    ],
    fields: [
      { key: "module_key", label: "Key", required: true },
      { key: "module_name", label: "Nombre", required: true },
      { key: "module_group", label: "Grupo" },
      { key: "module_icon", label: "Icono" },
      { key: "module_description", label: "Descripcion" },
      { key: "module_actions", label: "Acciones (JSON)" },
      { key: "is_active", label: "Activo", type: "checkbox" },
      { key: "sort_order", label: "Orden", type: "number" },
    ],
    initialValues: { is_active: true },
  },
  api_permissions: {
    key: "api_permissions",
    path: "/api_permissions",
    title: "Permisos API",
    description: "Permisos por perfil y modulo.",
    table: "api_permissions",
    idKey: "perm_id",
    orderBy: "perm_id",
    searchColumns: ["prof_id", "module_id"],
    columns: [
      { key: "prof_id", label: "Perfil ID" },
      { key: "module_id", label: "Modulo ID" },
      { key: "can_menu", label: "Menu" },
      { key: "can_show", label: "Ver" },
    ],
    fields: [
      { key: "prof_id", label: "Perfil ID", type: "number", required: true },
      { key: "module_id", label: "Modulo ID", type: "number", required: true },
      { key: "can_menu", label: "Menu", type: "checkbox" },
      { key: "can_show", label: "Ver", type: "checkbox" },
      { key: "can_add", label: "Crear", type: "checkbox" },
      { key: "can_edit", label: "Editar", type: "checkbox" },
      { key: "can_delete", label: "Eliminar", type: "checkbox" },
      { key: "custom_actions", label: "Acciones (JSON)" },
    ],
  },
  api_user_overrides: {
    key: "api_user_overrides",
    path: "/api_user_overrides",
    title: "Overrides API",
    description: "Excepciones por usuario.",
    table: "api_user_overrides",
    idKey: "override_id",
    orderBy: "override_id",
    searchColumns: ["user_id", "module_id"],
    columns: [
      { key: "user_id", label: "Usuario ID" },
      { key: "module_id", label: "Modulo ID" },
      { key: "can_menu", label: "Menu" },
      { key: "can_show", label: "Ver" },
    ],
    fields: [
      { key: "user_id", label: "Usuario ID", type: "number", required: true },
      { key: "module_id", label: "Modulo ID", type: "number", required: true },
      { key: "can_menu", label: "Menu", type: "checkbox" },
      { key: "can_show", label: "Ver", type: "checkbox" },
      { key: "can_add", label: "Crear", type: "checkbox" },
      { key: "can_edit", label: "Editar", type: "checkbox" },
      { key: "can_delete", label: "Eliminar", type: "checkbox" },
      { key: "custom_actions", label: "Acciones (JSON)" },
      { key: "expires_at", label: "Expira", type: "date" },
    ],
  },
  paysheet: {
    key: "paysheet",
    path: "/paysheet",
    title: "Nomina",
    description: "Planillas de pago por periodo.",
    table: "paysheets",
    idKey: "paysh_id",
    orderBy: "paysh_id",
    searchColumns: ["paysh_status"],
    columns: [
      { key: "std_id", label: "Estudio ID" },
      { key: "period_id", label: "Periodo ID" },
      { key: "paysh_status", label: "Estado" },
      { key: "paysh_total_cop", label: "Total COP" },
    ],
    fields: [
      { key: "std_id", label: "Estudio ID", type: "number", required: true },
      { key: "period_id", label: "Periodo ID", type: "number", required: true },
      { key: "paysh_total_usd", label: "Total USD", type: "number" },
      { key: "paysh_total_eur", label: "Total EUR", type: "number" },
      { key: "paysh_total_cop", label: "Total COP", type: "number" },
      { key: "paysh_status", label: "Estado" },
      { key: "paysh_notes", label: "Notas" },
    ],
    initialValues: { paysh_status: "DRAFT" },
  },
  massive_liquidation: {
    key: "massive_liquidation",
    path: "/massive_liquidation",
    title: "Liquidacion masiva",
    description: "Carga masiva de streams para liquidaciones.",
    table: "models_streams",
    idKey: "modstr_id",
    orderBy: "modstr_id",
    searchColumns: ["modstr_period"],
    columns: [
      { key: "modacc_id", label: "Cuenta ID" },
      { key: "modstr_date", label: "Fecha" },
      { key: "modstr_period", label: "Periodo" },
      { key: "modstr_earnings_value", label: "Ingreso" },
    ],
    fields: [
      { key: "modacc_id", label: "Cuenta ID", type: "number", required: true },
      { key: "modstr_date", label: "Fecha", type: "date", required: true },
      { key: "modstr_period", label: "Periodo", required: true },
      { key: "modstr_earnings_value", label: "Ingreso", type: "number", required: true },
    ],
  },
};
